name: django-strict-fields
channels:
  - conda-forge
dependencies:
  - python==3.11.3
  - poetry==1.5.1
  - pip==23.1.2
variables:
  DATABASE_URL: "postgres://postgres@localhost:5432/strict_fields_local"
  EXEC_WRAPPER: ""
